export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && . "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && . "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
export PATH=~/.local/bin:$PATH

export PATH="/opt/homebrew/opt/awscli@1/bin:$PATH"


export VIMINIT='source $MYVIMRC'
export MYVIMRC='~/.config/nvim/init.vim'
